### ISSUE TITLE
Add installation steps to Docs

### ISSUE THREAD

**Issue by mugbug** [mugbug/PaintAndBrush#1]
Describe how to install this package using SPM and Cocoapods

**Comment by mariorsjr** [comment]
hi, do you still need help with this issue? I would like to help 

edit: already created the pull request: https://github.com/mugbug/PaintAndBrush/pull/7

**Comment by mariorsjr** [comment]
@mugbug created this PR https://github.com/mugbug/PaintAndBrush/pull/8 to reflect the changes to version 0.2.0
